import type { Metadata } from 'next';
import './globals.css';
import { Albert_Sans, Young_Serif } from 'next/font/google';
import Header from '@/components/Header';
import ReduxProvider from '@/lib/redux/ReduxProvider';
import { Toaster } from '@/components/ui/toaster';
import AuthProvider from '@/provider/AuthProvider';
const getYoung = Young_Serif({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-young',
});
const getAlbert = Albert_Sans({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-albert',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${getAlbert.variable} ${getYoung.variable} antialiased`}
      >
        <AuthProvider>
          <ReduxProvider>
            <Header />
            {children}
            <Toaster />
          </ReduxProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
